In [10]:
import numpy as np

In [11]:
#how to create array
a = np.array([1,2,3,4,5])
print(a)

[1 2 3 4 5]


In [12]:
type(a)

numpy.ndarray

In [13]:
#creating a 2d array
a2 = np.array([[1,2,3,4,5],[6,7,8,9,10]])
print(a2)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]


In [14]:
#creating a 3d array
a3 = np.array([[[1,2,3],[4,5,6]],[[5,6,7],[8,9,10]]])
print(a3)

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 5  6  7]
  [ 8  9 10]]]


In [15]:
print(a2.shape) #gives number of rows and columns
print(a2.ndim)  #gives dimention of array
print(a2.dtype) #datatype of elements in array

(2, 5)
2
int64


In [16]:
print(np.arange(10)) #print no. till given range
print(np.arange(1,11))
print(np.arange(1,11,2))

[0 1 2 3 4 5 6 7 8 9]
[ 1  2  3  4  5  6  7  8  9 10]
[1 3 5 7 9]


In [17]:
np.random.randint(1,11, size=(2,3))  #to create array

array([[ 1,  2,  8],
       [10,  5,  2]], dtype=int32)

In [18]:
x = np.array([[7,2,3],
              [2,5,2],
              [3,5,1]])
y = np.array([[1,8,3],
              [3,7,2],
              [2,5,3]])
print(x)
print(y)

[[7 2 3]
 [2 5 2]
 [3 5 1]]
[[1 8 3]
 [3 7 2]
 [2 5 3]]


In [19]:
#matrix multiplication
print(x*y)  #or
print(x@y)

[[ 7 16  9]
 [ 6 35  4]
 [ 6 25  3]]
[[19 85 34]
 [21 61 22]
 [20 64 22]]


In [21]:
np.dot(x,y)  #matrix multiplication method - dot

array([[19, 85, 34],
       [21, 61, 22],
       [20, 64, 22]])

In [22]:
x.prod()  #product of all elements of the array

np.int64(12600)

In [24]:
#mean of all the elements
print(x.mean())
print(y.mean())

3.3333333333333335
3.7777777777777777


In [25]:
print(x)

[[7 2 3]
 [2 5 2]
 [3 5 1]]


In [27]:
x.mean(axis = 0) #column wise mean - axis = 0

array([4., 4., 2.])

In [28]:
y.mean(axis = 1) #row wise mean (axis=1)

array([4.        , 4.        , 3.33333333])

In [29]:
print(x.sum())
print(x.std()) #std deviation
print(x.var()) #variance

30
1.8257418583505538
3.3333333333333335


In [30]:
a = np.array([1,2,3,4,5,6,7,8,9])
print(np.percentile(a,25)) #1st quartile
print(np.percentile(a,50)) #median
print(np.percentile(a,75)) #3rd quartile

3.0
5.0
7.0


In [ ]:
b = np.random.randint(1,11) 
print(b)

9


In [35]:
b = np.random.randint(1,100,(5,5)) #size of matrix
print(b)

[[ 4 16 57 13 25]
 [65 17 54 55 93]
 [70 80 84 29 95]
 [45 58 27 22 83]
 [99 21 87  6 84]]


In [36]:
x = np.random.randint(1,11,(5,5))
print(x)

[[ 8 10  2 10  1]
 [ 8  8  2  2  5]
 [ 2  2  5  8  2]
 [ 8  2  9  8  7]
 [ 5  9  8 10  7]]


In [37]:
print(x[0]) #1st row
print(x[0,1]) #1st row and 2nd column's first element
print(x[-1])

print(x[:3])
print(x[3:])

[ 8 10  2 10  1]
10
[ 5  9  8 10  7]
[[ 8 10  2 10  1]
 [ 8  8  2  2  5]
 [ 2  2  5  8  2]]
[[ 8  2  9  8  7]
 [ 5  9  8 10  7]]
