In [1]:
import numpy as np

In [2]:
#how to create array
a = np.array([1,2,3,4,5])
print(a)

[1 2 3 4 5]


In [3]:
type(a)

numpy.ndarray

In [4]:
#creating a 2d array
a2 = np.array([[1,2,3,4,5],[6,7,8,9,10]])
print(a2)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]


In [6]:
#creating a 3d array
a3 = np.array([[[1,2,3],[4,5,6]],[[5,6,7],[8,9,10]]])
print(a3)

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 5  6  7]
  [ 8  9 10]]]


In [ ]:
print(a2.shape) #gives number of rows and columns
print(a2.ndim)  #gives dimention of array
print(a2.dtype) #datatype of elements in array

(2, 5)
2
int64


In [11]:
print(np.arange(10)) #print no. till given range
print(np.arange(1,11))
print(np.arange(1,11,2))

[0 1 2 3 4 5 6 7 8 9]
[ 1  2  3  4  5  6  7  8  9 10]
[1 3 5 7 9]


In [15]:
np.random.randint(1,11, size=(2,3))  #to create array

array([[10, 10,  5],
       [ 9,  6,  8]], dtype=int32)

In [16]:
x = np.array([[7,2,3],
              [2,5,2],
              [3,5,1]])
y = np.array([[1,8,3],
              [3,7,2],
              [2,5,3]])
print(x)
print(y)

[[7 2 3]
 [2 5 2]
 [3 5 1]]
[[1 8 3]
 [3 7 2]
 [2 5 3]]
